### ISSUE TITLE
Collapse repositories

### ISSUE THREAD

**Issue by RichardLitt** [in-development-ca/welcome#4]
At the moment, we have five or so documentation repositories with no actual code in them. I wonder; could we just put all of the information in one repository? I don't see a need for lots of repositories right now.

When we have a need beyond document storage, we could split them out again, but for now, collapsing will provide an easy way to work on documents.

**Comment by dxnn** [comment]
Sounds good to me!

**Comment by RichardLitt** [comment]
I've collapse and deleted `minutes`, `curricula`, and `projects`. After some brief thinking, I also moved `bizdocs` here. At this stage, there's really no difference to business docs and other things. We can make a folder here, if we need to. For now, this is done. 

I've kept the website in its own repository.
